name: Master Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

steps:
  - name: Checkout Produce/Consume Scala example
    uses: actions/checkout@v1

  - name:
    run:  sdk install sbt

  - name: Sbt Unit Tests
    run: sbt test