name: Master Workflow

on:
  push:
    branches:
      - 'master'

jobs:
  main:
    name: Master Workflow Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Produce/Consume Scala example
        uses: actions/checkout@v1

      - name: Install SDKMAN
        run: curl -s "https://get.sdkman.io" | bash

      - name: Install SBT
        run:  source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install sbt

      - name: Compile project
        run: sbt compile

      - name: Run test
        run: sbt test